### ISSUE TITLE
Adding new image to RNN captioning

### ISSUE THREAD

**Issue by vinayak618** [Burton2000/CS231n-2017#1]
how do i add my .jpg file and check the caption output of the algorithm?

**Comment by Burton2000** [comment]
Hey sorry for the delayed reply. 

The RNN/LSTM captioning models are trained on features extracted  (4096 dimensions) from the COCO images, these features are the dataset given to us not the raw images. 
To test your own images you would have to know how they extract these features from the images (probably a CNN) and extract features from your test image in the same way. As we don't have access to the model they used it's probably not possible.

On top of that they have reduced the dimension further from 4096 to 512 using PCA (check the section under Microsoft COCO in RNN_captioning notebook). 

If you can extract the feature vector from your image then checking the caption is the simple bit and the code below shows how to do it, just place it in a cell right at the end of the notebook.

```
# Load an image
test_im = plt.imread('./kitten.jpg')
plt.imshow(test_im)
plt.show()

# Dimension reduction of test image would go here 
# TODO

# A placeholder input to use as input to the model.
test_input = np.ones([1,512])  # Use

# Forward pass of the model.
cap_sample = small_rnn_model.sample(test_input )
cap_sample = decode_captions(cap_sample, data['idx_to_word'])
print(cap_sample)
```
