### ISSUE TITLE
Are these solutions correct?

### ISSUE THREAD

**Issue by vinitnayak87** [Burton2000/CS231n-2017#6]
I'm starting this course just by watching it on YouTube. Don't know a way to verify my work.
Do you know if your solutions are correct (not to suggest that they aren't, but curious)?

**Comment by Burton2000** [comment]
In pretty much all the notebooks you have to complete there is tests that need to pass to see if your solutions work. All the tests are passing in my solutions so yes I am pretty confident they are correct.

**Comment by vinitnayak87** [comment]
Got it, thanks.
