### ISSUE TITLE
A question on rnn_layer

### ISSUE THREAD

**Issue by nihuo76** [Burton2000/CS231n-2017#7]
Hi, I am also doing assignment 3 of CS231n. Yet I didn't get the correct number for the function `rnn_backward`. My code looks like this:
```python
for t in reversed(range(T)):
        dh[:,t,:]= dprev_h + dh[:,t,:]
        dx[:,t,:], dprev_h, dWx_temp, dWh_temp, db_temp = rnn_step_backward(dh[:,t,:], cache[t])
        dWx += dWx_temp
        dWh += dWh_temp
        db += db_temp
```
My cache is also a list of tuple of numpy array and every else is the same. Yet I did not get the correct number. May I ask if the reason of this weird result?

**Comment by Burton2000** [comment]
Looking at that bit of code everything seems fine there. Do the tests for rnn_step_backward function all pass? Also is dprev_h initialized to zeros before the for loop?

**Comment by nihuo76** [comment]
Hi, thank you for your response. The tests for rnn_step_backward is successful and returns a error at `e-9`. I also intialize dprev_h to be zero before the for loop.

**Comment by Burton2000** [comment]
After the for loop do you return the last hidden state gradient, so you set `dh0 = dprev_h`

**Comment by nihuo76** [comment]
Hi, I did that. But a weird result happens that all gradient with respect to x,Wx,Wh are wrong in my version. It is just so weird.
